### ISSUE TITLE
Time displays incorrectly when using mod/datapack huds

### ISSUE THREAD

**Issue by supersaiyansubtlety** [CmdrJane/time-and-wind#1]
I've installed taw, customized the time, and verified that day/night length have actually changed. 

Then I checked if [minihud's](https://www.curseforge.com/minecraft/mc-mods/minihud) time display line and it appeared to be advancing at vanilla speeds. 

I also tried [ModularHUD's](https://www.curseforge.com/minecraft/customization/modularhud) time display and it was identical to minihud's. 

It seems some value isn't being synced to the client properly?

**Comment by CmdrJane** [comment]
i gonna look into it but i guess i already know the problem. this is very likely to fact that duration of day in vanilla game is fixed 24000 and vanilla client does not sync duration by default. So all mod that calculates time of day use time % 24000 but since taw implements own variable for cycle duration this is the problem.

**Comment by supersaiyansubtlety** [comment]
Would it make sense to send the client the vanilla-equivalent version of the time?
So if taw has a day of 36000 ticks, send the client 6000 ticks (vanilla noon) at 18000 ticks (taw configured noon).

**Comment by CmdrJane** [comment]
> 
> 
> Would it make sense to send the client the vanilla-equivalent version of the time?
> So if taw has a day of 36000 ticks, send the client 6000 ticks (vanilla noon) at 18000 ticks (taw configured noon).

This makes no sense, the problem is that vanilla doesn have field where it keeps duration of day, its just stack push of 24000L flat. So any mod that does calculation just using modulo 24000L. And taw does not messes around tick timer itself so only possible solution for this is that mod author of mod X should add config for those values or compatibility for this mod.

I'm going to mixin for [Simple Utilities](https://www.curseforge.com/minecraft/mc-mods/simple-utilitiesl) but  thats it since i cant fix everyone else mod by hand. Im going to make compat request for minihud but it was last updated like 3 month ago so cant promise anything

**Comment by supersaiyansubtlety** [comment]
Ok, makes sense, thanks. 

Should this issue be closed now?

**Comment by CmdrJane** [comment]
i guess so.

Also you can use Simple Utilities for since latest version of  taw support custom time for it

**Comment by supersaiyansubtlety** [comment]
I just noticed that minihud actually has a `timeDayDivisor` setting which probably should make it compatible if you make it match the total duration set by taw (may require day and night to be same length), but the setting seems to only affect the time in ticks, not the formatted time.  

I'm going to open an issue over on minihud's repo about this.
